version: '2'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    labels: 
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/docker-volumes/nginx/vhost.d:/etc/nginx/vhost.d
      - /var/docker-volumes/nginx/conf.d:/etc/nginx/conf.d
      - /var/docker-volumes/nginx/certs:/etc/nginx/certs:ro
      - /var/docker-volumes/nginx/html:/usr/share/nginx/html

  nginx-gen:
    image: jwilder/docker-gen
    container_name: docker-gen
    restart: always    
    labels: 
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /var/docker-volumes/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/docker-volumes/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

  mousehouse:
    image: sfu/mousehouse
    restart: always
    container_name: mousehouse
    env_file:
      - mousehouse.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    external:
      name: nginxproxy
